# Generated by Django 5.0.6 on 2024-05-30 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0002_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
