# Generated by Django 5.0.6 on 2024-06-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0005_testimonial_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintingServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='printingservice/images')),
            ],
        ),
    ]
