# Generated by Django 5.0.6 on 2024-06-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0007_itservices_photographyservices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItServices',
            new_name='GetItServices',
        ),
        migrations.RenameModel(
            old_name='PhotographyServices',
            new_name='GetPhotographyServices',
        ),
    ]
