# Generated by Django 5.0.6 on 2024-06-25 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0008_rename_itservices_getitservices_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='itservice/images')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('image', models.ImageField(upload_to='photographyservice/images')),
            ],
        ),
    ]
