# Generated by Django 5.0.6 on 2024-06-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_app', '0009_itservices_photographyservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='itservices',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='photographyservices',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
