# Generated by Django 4.1.13 on 2024-06-02 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='name',
            new_name='title',
        ),
    ]
