# Generated by Django 4.1.13 on 2024-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0002_rename_name_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='defaultpost.jpg', upload_to='post_pics'),
        ),
    ]
