# Generated by Django 4.1.13 on 2024-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_image',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='post_pics'),
        ),
    ]
