# Generated by Django 4.1.13 on 2024-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_comment_commenter_image_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_website',
            field=models.CharField(default='hello', max_length=100),
        ),
    ]
