# Generated by Django 4.1.13 on 2024-05-31 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_comment_commenter_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter_website',
            field=models.CharField(max_length=100),
        ),
    ]
