# Generated by Django 4.1.13 on 2024-06-01 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_alter_comment_commenter_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='defaultpost.jpg', upload_to='post_pics'),
        ),
    ]
