# Generated by Django 4.1.13 on 2024-06-01 10:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_remove_comment_parent_comment_comment_is_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_reply',
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replied_by', models.CharField(max_length=100)),
                ('reply_desc', models.CharField(max_length=300)),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog_app.comment')),
            ],
        ),
    ]
